### ISSUE TITLE
Remove projectId from queries for embeddings and zero-shot recommendations on for downloaded models

### ISSUE THREAD

**Issue by lumburovskalina** [code-kern-ai/refinery-gateway#33]
Currently the requests for the embeddings and zero shot recommendation require the projectId on the downloaded models page. This can be solved by setting the projectId as optional parameter and in this case all models should be returned.

**Comment by JWittmeyer** [comment]
removing the project id from the query would remove functionality. Currently, we filter for e.g. the zero-shot recommendations depending on the project selection.

That said an optional parameter might still be useful since the model download page might not need the filter
