### ISSUE TITLE
Refactor service requests, calls to other services

### ISSUE THREAD

**Issue by FelixKirsch** [code-kern-ai/refinery-gateway#36]
Service requests from refinery-gateway to other services, e.g. neural-search, embedder, etc., use the methods from util.service_requests.py. The service requests expect a JSON answer in the following form [content, status_code]. However, it is not needed to return the status_code explicitly, e.g. when using fastAPI as in all services.  The service_requests methods do not access the status_code in the JSON. This leads to returning empty strings as placeholders in some services.
Refactoring would require changes in service_requests.py as well as in the APIs of the concerned services.

**Comment by JWittmeyer** [comment]
done with https://github.com/code-kern-ai/refinery-gateway/pull/118
